name: Auto Tag on Merge

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          echo "Fetching all tags from the remote..."
          # Fetch all tags from the remote
          git fetch --tags
          
          # Check if git fetch succeeded
          if ($LASTEXITCODE -ne 0) {
            Write-Host "Failed to fetch tags from the remote."
            exit 1
          }

          echo "Attempting to get the latest tag..."
          try {
            # Attempt to get the latest tag
            $LATEST_TAG = git describe --tags --abbrev=0 2>$null
            if (-not $LATEST_TAG) {
                throw "No tags found"
            }
          }
          catch {
            # Fallback to USSFence[1.0.0.0] if no tags found
            $LATEST_TAG = "USSFence[1.0.0.0]"
          }
          
          Write-Host "Latest Tag: $LATEST_TAG"

          # Write the latest tag to the environment file so it can be used in the next step
          echo "LATEST_TAG=$LATEST_TAG" >> $env:GITHUB_ENV

      - name: Check if LATEST_TAG is set
        run: |
          # Print the environment variable in PowerShell
          Write-Host "LATEST_TAG from previous step: $env:LATEST_TAG"

      - name: Create new tag based on the latest tag
        run: |
          # Fetch the latest tag from the environment variable
          $LATEST_TAG = $env:LATEST_TAG

          Write-Host "LATEST_TAG value: $LATEST_TAG"
          
          # If the latest tag is USSFence[1.0.0.0], use it as the new tag
          if ($LATEST_TAG -eq "USSFence[1.0.0.0]") {
            Write-Host "Using the fallback tag: $LATEST_TAG"
            $NEW_TAG = "USSFence[1.0.0.0]"
          } else {
            # Extract version numbers from the tag (assumes format USSFence[major.minor.patch.build])
            $VERSION = $LATEST_TAG -replace "USSFence\[([0-9]+)\.([0-9]+)\.([0-9]+)\.([_
