name: Auto Tag on Merge

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          echo "Fetching all tags from the remote..."
          # Fetch all tags from the remote
          git fetch --tags

          # Try to get the latest tag, fall back to USSFence[1.0.0.0] if no tags exist
          echo "Attempting to get the latest tag..."
          try {
              $LATEST_TAG = git describe --tags --abbrev=0 2>$null
              if (-not $LATEST_TAG) {
                  throw "No tags found"
              }
          }
          catch {
              $LATEST_TAG = "USSFence[1.0.0.0]"
          }

          Write-Host "Latest Tag: $LATEST_TAG"

          # Write the latest tag to the environment file so it can be used in the next step
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

              Write-Host "Latest Tag...."

      - name: Check if LATEST_TAG is set
        run: |
          echo "LATEST_TAG from previous step: ${{ env.LATEST_TAG }}"

              Write-Host "End Check if LATEST_TAG is set Tag...."

      - name: Create new tag based on the latest tag
        run: |

          Write-Host "In Create new tag based on the latest tag"
          # Get the latest tag from the environment variable
          echo "Fetching the latest tag..."
          LATEST_TAG="${{ env.LATEST_TAG }}"

          echo "LATEST_TAG value: $LATEST_TAG"
          
          # If the latest tag is USSFence[1.0.0.0], use it as the new tag
          if [ "$LATEST_TAG" == "USSFence[1.0.0.0]" ]; then
            NEW_TAG="USSFence[1.0.0.0]"
          else
            # Extract version numbers from the tag (assumes format USSFence[major.minor.patch.build])
            VERSION=$(echo $LATEST_TAG | sed -E 's/USSFence\[([0-9]+)\.([0-9]+)\.([0-9]+)\.([0-9]+)\]/\1.\2.\3.\4/')
            echo "Extracted VERSION: $VERSION"

            # Increment the build number (last digit)
            IFS='.' read -r major minor patch build <<< "$VERSION"
            ((build
